name: teo-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.1
  - urllib3=1.26.8
  - beautifulsoup4=4.11.1
  - matplotlib=3.5.1
  - requests=2.27.1
  - pydantic=1.9.0
  - jsonpickle=2.2.0
  - plotly=5.7.0
  - jinja2=3.0.3
  - flask=2.1.2
  - pandas=1.4.1
  - pyscipopt=4.2.0
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0
    - amply==0.1.4
    - docutils==0.17.1
    - pulp==2.4
    - gurobipy==9.5.1